// Test de fumée : démarre le serveur sur un dossier temporaire et joue un parcours complet
// (comptes, brutes, arène, IA, campagne, amis, signalements, passe, salons coop/PvP, redémarrage sans perte).
const { spawn } = require('child_process');
const os = require('os'), path = require('path'), fs = require('fs');
const WebSocket = require('ws');
const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'brutes-'));
const PORT = 18097;
let srv;
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const start = () => { srv = spawn(process.execPath, [path.join(__dirname, '..', 'src', 'server.js')], { env: { ...process.env, PORT, DATA_DIR: dir }, stdio: 'inherit' }); return sleep(700); };
const base = `http://127.0.0.1:${PORT}/api`;
async function call(method, p, body, token) {
  const r = await fetch(base + p, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const j = await r.json();
  if (!r.ok) throw new Error(p + ' -> ' + r.status + ' ' + j.error);
  return j;
}
const assert = (c, m) => { if (!c) throw new Error('ÉCHEC ' + m); };
function client(token, bruteId) {
  const ws = new WebSocket(`ws://127.0.0.1:${PORT}/api/ws?token=${token}`);
  const c = { ws, msgs: [], send: (o) => ws.send(JSON.stringify(o)), last: (t) => [...c.msgs].reverse().find((m) => m.t === t) };
  ws.on('message', (m) => c.msgs.push(JSON.parse(m)));
  c.ready = new Promise((r) => ws.on('open', () => { c.send({ t: 'hello', brute: bruteId }); r(); }));
  return c;
}
async function clearLevelups(u) {
  const me = await call('GET', '/me', null, u.token);
  for (const x of me.account.brutes) if (x.levelup) await call('POST', '/brute/levelup', { brute: x.id, choice: 0 }, u.token);
}
(async () => {
  await start();
  const u = [];
  for (const n of ['Alice', 'Bob', 'Chloé']) u.push(await call('POST', '/register', { user: n, pass: 'secret' }));
  const b = [];
  for (const [i, h] of ['orc', 'elfe', 'naine'].entries()) b.push((await call('POST', '/brute/create', { name: 'Brute' + i, hero: h }, u[i].token)).brute);
  let f = await call('POST', '/fight/player', { brute: b[0].id, opponent: b[1].id }, u[0].token);
  console.log('arène OK, récompenses', JSON.stringify(f.fight.rewards[b[0].id]), 'or', f.account.gold);
  f = await call('POST', '/fight/ai', { brute: b[0].id, difficulty: 'facile' }, u[0].token);
  await clearLevelups(u[0]);
  f = await call('POST', '/fight/campaign', { brute: b[0].id, stage: 'c1' }, u[0].token);
  console.log('campagne', f.fight.winner === 0 ? 'gagnée' : 'perdue');
  console.log((await call('POST', '/friends/add', { name: 'Bob' }, u[0].token)).text);
  const fr = await call('GET', '/friends', null, u[1].token);
  assert(fr.requests.length === 1, "demande d'ami reçue");
  await call('POST', '/friends/accept', { id: fr.requests[0].id }, u[1].token);
  assert((await call('GET', '/friends', null, u[0].token)).friends.length === 1, 'amis');
  const rep = await call('POST', '/report', { type: 'bug', title: 'Le loup traverse le mur', text: "Pendant un combat le loup sort de l'écran." }, u[0].token);
  await call('POST', '/report/vote', { id: rep.report.id }, u[1].token);
  await call('POST', '/report/comment', { id: rep.report.id, text: 'Pareil chez moi' }, u[1].token);
  const reps = await call('GET', '/reports', null, u[2].token);
  assert(reps.reports[0].votes === 2 && reps.reports[0].comments.length === 1, 'signalements');
  await call('POST', '/profile', { motto: 'Je cogne donc je suis', avatar: 'barbare' }, u[0].token);
  const prof = await call('GET', '/profile?name=alice', null, u[1].token);
  assert(prof.profile.motto.startsWith('Je cogne'), 'profil');
  const me = await call('GET', '/me', null, u[0].token);
  console.log('passe xp', me.account.pass.xp, 'palier', me.account.pass.tier, 'quêtes', me.account.quests.map((q) => q.id + ':' + q.progress).join(' '));
  for (let i = 0; i < 3; i++) await clearLevelups(u[i]);
  const c = u.map((x, i) => client(x.token, b[i].id));
  await Promise.all(c.map((x) => x.ready));
  await sleep(300);
  c[0].send({ t: 'party_create', mode: 'coop_ai', difficulty: 'facile', public: false });
  await sleep(200);
  const pid = c[0].last('party').party.id;
  c[0].send({ t: 'party_invite', to: b[1].id });
  await sleep(200);
  assert(c[1].last('invite'), 'invitation reçue');
  c[1].send({ t: 'party_join', id: pid });
  await sleep(200);
  c[1].send({ t: 'party_ready', ready: true });
  await sleep(200);
  c[0].send({ t: 'party_start' });
  await sleep(400);
  const cf = c[1].last('fight');
  assert(cf && cf.fight.mode === 'coop_ai' && cf.fight.teams[0].length === 2, 'combat coop ' + JSON.stringify(c[0].last('info')));
  console.log('coop IA OK : équipes', cf.fight.teams.map((t) => t.map((x) => x.name).join('+')).join(' vs '), 'gagnant', cf.fight.winner);
  for (let i = 0; i < 3; i++) await clearLevelups(u[i]);
  c[0].send({ t: 'party_settings', mode: 'pvp', public: true });
  await sleep(300);
  assert(c[2].last('lobby') && c[2].last('lobby').parties.some((p) => p.id === pid), 'salon public listé');
  c[2].send({ t: 'party_join', id: pid });
  await sleep(200);
  c[2].send({ t: 'party_side', side: 1 }); c[1].send({ t: 'party_side', side: 0 });
  await sleep(150);
  c[1].send({ t: 'party_ready', ready: true }); c[2].send({ t: 'party_ready', ready: true });
  await sleep(200);
  c[0].send({ t: 'party_start' });
  await sleep(400);
  const pf = c[2].last('fight');
  assert(pf && pf.fight.mode === 'pvp' && pf.side === 1, 'pvp en équipes ' + JSON.stringify(c[0].last('info')));
  console.log('PvP OK', pf.fight.teams.map((t) => t.length).join('v'));
  for (let i = 0; i < 3; i++) await clearLevelups(u[i]);
  c[0].send({ t: 'party_settings', mode: 'coop_campaign', stage: 'c1' });
  await sleep(200);
  c[1].send({ t: 'party_ready', ready: true }); c[2].send({ t: 'party_ready', ready: true });
  await sleep(200);
  c[0].send({ t: 'party_start' });
  await sleep(400);
  const ccf = c[0].last('fight');
  assert(ccf && ccf.fight.mode === 'coop_campaign', 'campagne coop ' + JSON.stringify(c[0].last('info')));
  console.log('campagne coop OK, boss', ccf.fight.teams[1][0].name, 'gagnant', ccf.fight.winner);
  srv.kill('SIGTERM');
  await sleep(500);
  await start();
  const c2 = client(u[1].token, b[1].id);
  await c2.ready; await sleep(300);
  assert(c2.last('party') && c2.last('party').party && c2.last('party').party.id === pid, 'salon restauré après redémarrage');
  console.log('salon restauré après redémarrage : OK');
  console.log('stats', JSON.stringify(await call('GET', '/stats')).slice(0, 120));
  console.log('TOUT EST OK');
  srv.kill(); process.exit(0);
})().catch((e) => { console.error(e); if (srv) srv.kill(); process.exit(1); });
